---
- name: Pull Jenkins Docker image
  docker_image:
    name: "{{ jenkins_image }}"
    source: pull

- name: Run Jenkins container
  docker_container:
    name: jenkins
    image: "{{ jenkins_image }}"
    state: started
    published_ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: unless-stopped

- name: Wait for Jenkins to start on port 8080
  wait_for:
    port: 8080
    delay: 10
    timeout: 60

- name: Get Jenkins container ID
  command: docker ps -qf name=jenkins
  register: container_id
  changed_when: false

- name: Copy Docker install script into Jenkins container
  command: >
        docker exec -u 0 {{ container_id.stdout }} sh -c "curl -fsSL https://get.docker.com -o /tmp/dockerinstall &&
        chmod +x /tmp/dockerinstall"

- name: Install Docker inside Jenkins container
  command: >
        docker exec -u 0 {{ container_id.stdout }} sh -c "/tmp/dockerinstall"